project:
  type: website

website:
  title: Zero to Website with Quarto Workshop 
  description: "Zero to website with Quarto Workshop for Data Science Learning Community 2024"
  site-url: https://charlotte.quarto.pub/dslc24/
  image: thumbnail.jpeg
  open-graph: true 
  search: false
  page-footer: "Made with ❤️ and Quarto"
  sidebar:
    title: Zero to Website with Quarto Workshop 
    alignment: center
    style: docked
    logo: dslc_edu_line_white.png
    logo-alt: Data Science Learning Community Logo
    contents:
      - href: index.qmd
        text: Home
      - prework.qmd
      - materials.qmd
    tools:
      - icon: github
        href: https://github.com/cwickham/dslc-websites


format:
  html:
    mainfont: "Atkinson Hyperlegible"
    theme: [cosmo, styles.scss]